apiVersion: v1
kind: Pod
metadata:
  name: debug-hostpath
  namespace: default
spec:
  containers:
  - name: debug
    image: busybox:1.36
    command: ["sleep", "3600"]
    volumeMounts:
    - name: var-dir
      mountPath: /host/var
  volumes:
  - name: var-dir
    hostPath:
      path: /var
