apiVersion: v1
data:
    password: ENC[AES256_GCM,data:CpFaDBWUraQ=,iv:iqq7eKO2K+++v4kN2i1qG9bbscQ6W6sJElfPNIke3XE=,tag:fJlo5J7xcbFmII6mO4yo2g==,type:str]
    user: ENC[AES256_GCM,data:he2yFGA2Fvc=,iv:LM8awvmrFsDZim5i6lp3GAyCj9hmUhZPt4s98BI4YWI=,tag:gf+gPCQ+fER5qpRp0OKmBg==,type:str]
kind: Secret
metadata:
    name: test-secret
    namespace: linkding
type: Opaque
sops:
    age:
        - recipient: age15wqm7z3mc9xaz56yt6ymeplwtvfcga9ncy7eqd0vfpt7yts24yuqt72v6v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeE1LRzZFbmd1cWkvMnRE
            U1hVQ29pck1MSjd1OFV6VTcwTWFMcUxqL0ZvCmtkUEl0bDl2UWZ1eUJJcHlIR3g0
            a0V5Qnc1VFJzT1lyV09RTE1FS3NoRXMKLS0tIHU3MEhDaDVXekpZaTZGWnVoUGJJ
            N252cnhTRWpzME10SFZPTEJkYi9Da1EKeFqv8AE4tKsF0MUTddUaykKxcnhEUIiy
            IWaq0Ry10lWW7FVx0nEwgYjX2HE3BnAhWneLzNQrsVhpgKjum85tNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T00:37:57Z"
    mac: ENC[AES256_GCM,data:dBTchdw4Au9p+ECwOEW2a/8NKe5xxlgwo4t0hPrTgdx9lgvc9TYyKvVbPCVKuceBBvUTc4CWbBSbytrRhFkgyw39KgabiEkdH+tPs2xEqgi2CUoUEhp4yh8FlUET4FgIIbI3oNfygJm+/vd53fWVcN7VBoR6ZCvgC2OM+kVXH0s=,iv:YWczIrjdc8TMvDb5+ajjf46zGaKTGy1xxYGnOsbXEFA=,tag:5S7yqdq0RO3WQKjt4yNIrw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
