# FILE: clusters/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux-system/
  - ./apps.yaml
  # - ./storage-provisioner.yaml  <-- DELETE THIS LINE