# FILE: apps/base/linkding/storage.yaml
# PURPOSE: To claim the statically defined NFS PersistentVolume.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
spec:
  # An empty storageClassName allows this PVC to bind to the PV
  # we defined, which also has no storage class.
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi