# FILE: apps/base/linkding/storage.yaml
# PURPOSE: To request dynamically provisioned storage from the NFS provisioner.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
spec:
  # This now requests storage from our dynamic NFS provisioner.
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi