apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:BiO4aGFZq8OawJy26/zCCeyooX0VMcMJ2oNzSpg1o/JRJ6c/iC5dPBlrzqRUO5Wcu6cY0QS9BSs=,iv:Q+ZcaURC1J9UL4wMdkD7Kglv/QO6oxrnIQtmy9Q8hEc=,tag:qnYYxNqrzhZvmf7TLNKCVQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate-container-env
sops:
    age:
        - recipient: age15wqm7z3mc9xaz56yt6ymeplwtvfcga9ncy7eqd0vfpt7yts24yuqt72v6v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Zk5xRFFxUE1PdTU1MVlm
            NlhmTWVwTmpJWVk5WmQ0L2xYRFJyeFJZMzFBCm5ONTZFb3VSOGgwS1paL0VFZ2xS
            MHd2bnZ5MXJpYklnWU5VNmRBVWlWTFEKLS0tIG5GaGYvNTFRN0xjeXdvV2Y2Kytj
            VUZWRTJ0dUc5QTRDSk0vaFFSV2ViVzgKJIc9c3icYKUGI3bBqwLch4gVToehs3GI
            NhDc4LeWf/qNWf+yWnbALjguSfmhbJ+M7P/qfKieB+CVUTvk2ejtWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-20T00:21:19Z"
    mac: ENC[AES256_GCM,data:P0I+5o/zFF/xSpFSaqPLPkP4+ys9X20+mObQQAylq8nxhnL9/lRUttisOEmYE4MLf7NDO/IufFeUWICtbltKq/31os5vbKMEgEzynoCM4UJgflg+QEVEWMtgf/e19gMTH3bYDgiv1JN4qk9s/VqGo1ddfTSLJ6YLk1+bYGdKFuE=,iv:/wz/bi2KAk2kK5GhvoPfzcqemVZ9rqAx1mzxoI5DmOI=,tag:6ApCFOMAaiEuDO2jywTh9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
